(function (window) {
    'use strict';

    var VP = window.VP;

    var FRASES = {
        clic: [
            '¡Miau! ¿Me llamabas? ♡', '¡Ronroneo para ti!', '¡Aquí estoy, amigui!',
            '¡Presente!', '¿Me buscabas? Ya llegué.', '¡Te escucho!',
            'No me fui muy lejos.', '¿Un saludito para mí?', 'Aquí estoy, listo para ayudar.',
            '¡Hola otra vez!',
            '¡Ey, aquí estoy!',
            'Ese toque llegó directo al corazón.',
            '¡Me activaste el modo compañero!',
            '¿Listo para seguir viendo?',
            '¡Qué bueno verte por aquí!',
            'Toc, toc... Mochi al habla.',
            '¡Un clic y aparecí!',
            'Siempre atento a tus señales.',
            '¡Hola, qué gusto encontrarte!',
            '¿Qué hacemos ahora?',
            '¡Me quedo cerquita!',
            '¡Estoy aquí contigo!',
            '¡Ese toque me despertó!',
            '¡Presente, con orejas listas!',
            'Aquí va un saludo rápido.',
            '¡Te acompaño en la aventura!',
            '¿Seguimos con el video?',
            '¡Qué sorpresa tan agradable!',
            'Un clic, una sonrisa.',
            '¡Listo para la próxima!',
            '¡No pierdo detalle!',
            'Gracias por saludarme.',
            '¡Me encanta cuando apareces!',
            '¡Aquí, al pie del video!',
            '¿Quieres que te cuente algo?',
            '¡Tengo toda mi atención puesta!',
            '¡Qué bueno compartir este rato!',
            'Un saludito de vuelta.',
            '¡Modo compañía activado!',
            '¡Me alegra estar aquí!'
        ],
        caricias: [
            '¡Me haces muy feliz! ♡', '¡Otra caricia? ¡Sí!', '¡Ronroneo activado!',
            '¡Qué buen mimo!', 'Gracias, amigui. ✨', '¡Ese cariñito se sintió genial!',
            'Prrr… qué a gusto.', '¡Me sacaste una sonrisa!',
            '¡Ese mimo llegó justo a tiempo!',
            'Se me aflojaron hasta las orejitas.',
            '¡Qué manera tan bonita de saludar!',
            'Prrr... podría quedarme así un buen rato.',
            '¡Gracias por consentirme!',
            'Un poquito más y me derrito.',
            '¡Me dejaste el ánimo por las nubes!',
            'Ese toque fue pura ternura.',
            '¡Qué suave se siente!',
            'Prrr, mi motorcito está feliz.',
            '¡Me hacía falta un mimo así!',
            'Ya estoy moviendo la cola de alegría.',
            '¡Qué detalle tan cariñoso!',
            'Ese cariño me recargó la energía.',
            '¡Se siente bonito tenerte cerca!',
            'Mimo recibido y guardado con cariño.',
            '¡Mis mejillas se pusieron contentas!',
            'Prrr... aprobación total.',
            '¡Qué gusto que me acaricies!',
            'Me dejaste en modo felicidad.',
            '¡Otro toque de buena onda!',
            'Ese cariño hizo cosquillas.',
            '¡Estoy brillando de contento!',
            'Mi cola acaba de decir gracias.',
            '¡Qué buen momento para un mimo!',
            'Se siente como un abrazo pequeñito.',
            '¡Me guardo este cariñito!',
            'Prrr... compañía de primera.',
            '¡Me pusiste de buen humor!',
            'Gracias por tratarme con tanto cariño.'
        ],
        curiosidad: [
            '¡Mira qué detalle tan curioso!', 'Eso sí que no me lo esperaba.',
            '¡Qué interesante! Quiero saber más.', 'Ese detalle merece una segunda mirada.',
            '¡Vaya giro! Me dio curiosidad.', 'Mmm, ahí hay algo llamativo.',
            '¡Qué buena observación la del video!', 'Ese momento sí captura la atención.',
            'Ese cambio de escena invita a mirar otra vez.',
            '¡Qué detalle tan fácil de pasar por alto!',
            'La escena dejó una pista interesante.',
            'Ese gesto cuenta más de lo que parece.',
            '¡El ritmo cambió justo en ese momento!',
            'Me intriga lo que acaba de aparecer.',
            'Ese contraste le da otro aire a la escena.',
            'Hay algo en ese momento que destaca.',
            '¡Qué forma tan curiosa de resolverlo!',
            'Ese pequeño cambio modifica la escena.',
            'Me fijé en cómo reaccionó justo ahí.',
            '¡Qué buena pausa para notar los detalles!',
            'La escena parece esconder una segunda lectura.',
            'Ese movimiento llamó mi atención.',
            '¡Mira cómo cambió el ambiente!',
            'Ese detalle combina muy bien con el momento.',
            'Qué interesante la manera en que lo muestran.',
            '¡Ese encuadre dirige la mirada justo ahí!',
            'Hay un cambio sutil en el tono de la escena.',
            'Me llamó la atención ese pequeño gesto.',
            '¡Qué buen momento para hacer una pausa!',
            'La reacción fue tan rápida como reveladora.',
            'Ese detalle añade algo inesperado.',
            '¡La escena acaba de tomar otro rumbo!',
            'Me gusta cómo ese elemento destaca en pantalla.',
            'Ese instante conecta muy bien con lo anterior.',
            '¡Qué curioso cómo cambia la impresión al verlo!',
            'Ese detalle merece quedarse en la memoria.',
            'La siguiente escena quizá aporte otra pista.',
            'Hay algo nuevo que observar en esta parte.'
        ],
        pensando: [
            'Mmm… déjame pensarlo.', '¡Estoy ordenando mis ideas!',
            'Dame un segundo para conectar las piezas.', 'A ver… creo que ya lo tengo.',
            'Estoy buscando la mejor forma de decirlo.', 'Mmm, voy a pensarlo con calma.',
            'Un momento; estoy juntando las pistas.',
            'A ver, voy a ordenar este pequeño rompecabezas.',
            'Estoy repasando lo que acaba de pasar.',
            'Dame un instante para encontrar el hilo.',
            'Quiero asegurarme de no saltarme ningún detalle.',
            'Mmm, estoy comparando las pistas.',
            'Voy a mirar esta idea desde otro ángulo.',
            'Un segundo, mi cabeza está haciendo conexiones.',
            'Estoy buscando qué detalle encaja mejor.',
            'Déjame juntar lo importante primero.',
            'Creo que hay una pista escondida por aquí.',
            'Estoy comprobando cómo se relaciona todo.',
            'A ver... una cosa lleva a la otra.',
            'Quiero encontrar una respuesta clara.',
            'Estoy separando los detalles de lo demás.',
            'Mmm, esa parte merece pensarse un poco.',
            'Voy despacio para no perder ninguna pista.',
            'Deja que mis ideas se acomoden un momento.',
            'Estoy buscando una conexión entre esas escenas.',
            'A ver si encuentro el detalle que lo explica.',
            'Un instante; estoy revisando mi razonamiento.',
            'Ya casi termino de ordenar mis ideas.',
            'Estoy pensando en la forma más sencilla de contarlo.',
            'Mmm... quizá la clave está en ese cambio.',
            'Voy a conectar esto con lo que vimos antes.',
            'Necesito un segundo para darle una vuelta.',
            'Estoy eligiendo qué pista importa más.',
            'Déjame revisar esa idea una vez más.',
            'Creo que ya veo por dónde va.',
            'Estoy armando una respuesta paso a paso.',
            'Un momento más y te cuento lo que pienso.'
        ],
        sinContexto: [
            'Aún no llegaron subtítulos, amiguo. Avísame cuando empiecen.',
            'No encuentro subtítulos por aquí; igual te acompaño.',
            'Todavía no tengo suficiente contexto para comentar.',
            'Espero las próximas líneas y busco un detalle.',
            'Por aquí sigo, atento a los subtítulos.',
            'Cuando empiece el diálogo, me uno.',
            'Aún no aparecen pistas del video.',
            'Esperaré un poquito más antes de comentar.',
            'Por ahora no tengo líneas para seguir, pero aquí estoy.',
            'Todavía no aparece texto que pueda leer.',
            'Me quedo atento por si llegan subtítulos.',
            'Aún no hay suficiente información en pantalla.',
            'Espero un poco más; quizá el contexto aparece enseguida.',
            'Todavía no encuentro palabras para seguir la escena.',
            'Cuando aparezcan más pistas, las reviso contigo.',
            'Por ahora solo puedo observar y esperar.',
            'Parece que los subtítulos aún no arrancan.',
            'Me faltan algunas pistas para hacer un comentario.',
            'Sigo pendiente, por si empieza el diálogo.',
            'Aún no tengo texto suficiente para orientarme.',
            'Esperaré a que llegue un poco más de contexto.',
            'Todavía no veo subtítulos que pueda aprovechar.',
            'Aquí sigo, atento a cualquier línea nueva.',
            'Por ahora el contexto está un poquito silencioso.',
            'Me vendrían bien unas líneas más para comentar.',
            'Aún no encuentro de qué agarrarme para reaccionar.',
            'Voy a esperar otra pista antes de sacar conclusiones.',
            'Todavía no tengo suficiente información para aportar.',
            'Cuando haya más texto, vuelvo a intentarlo.',
            'Por aquí sigo, esperando el momento adecuado.',
            'Aún no puedo seguir la conversación del video.',
            'Me quedo cerca mientras llegan más subtítulos.',
            'Todavía falta un poco de contexto para comentar.',
            'Espero que aparezcan más pistas en la próxima escena.',
            'Aún no hay suficiente texto para entender el tema.',
            'Sigo atento; no quiero inventarme lo que pasa.',
            'Cuando tenga más contexto, te cuento algo útil.',
            'Por ahora espero en silencio, pero sigo aquí.'
        ]
    };
    VP._mochiMacho.FRASES = FRASES;
})(window);
