(function (window) {
    'use strict';

    var VP = window.VP;

    /* =====================================================================
       2. DIÁLOGOS Y TEXTOS
       ===================================================================== */
    var SALUDOS = [
        '¡Hola! Soy Mochi, tu asistente curioso ♡', '¡Miau! Ya llegué para acompañarte ✨',
        '¡Qué bueno verte! ¿Vemos algo juntos?', '¡Listo para la aventura! ¿Qué veremos?',
        '¡Hola! Me alegra compartir este rato contigo. ♡', '¡Ya estoy aquí! ¿Qué historia nos espera?',
        '¿Listo para darle play? Yo ya estoy preparado.', '¡Qué gusto verte por aquí, amigui!',
        'Acomódate, que ya estoy listo para acompañarte.', '¿Qué veremos hoy? Tengo curiosidad.',
        '¡Llegaste justo a tiempo para la función!', 'Aquí estoy, preparado para una nueva aventura.',
        '¡Hola, hola! ¿Qué ponemos?', 'Ya encontré mi rinconcito. ¿Empezamos?',
        '¡Buenas! Prometo no tapar la pantalla.', 'Listo y atento. Tú eliges el video.',
        '¡Qué emoción! Una historia nueva por descubrir.', '¡Hola! Hoy también puedo hacerte compañía.',
        'Me alegra coincidir contigo. ¿Le damos play?', '¡Presente! ¿Qué vamos a mirar?',
        'Aquí me tienes, listo para ver contigo.', '¡Ya llegué! Guárdame un lugarcito.',
        'Un video y buena compañía: suena perfecto.', '¡Hola, amigui! ¿Qué aventura elegimos?',
        'Ya estoy cómodo. Cuando quieras, empezamos.', '¡Listo para descubrir algo interesante!',
        'Qué gusto volver a este rinconcito contigo.', '¡Hola! A ver qué detalle curioso encontramos.',
        'La función está por comenzar; yo ya estoy listo.', '¡Qué bueno que volviste! ♡',
        'Preparado, atento y sin spoilers. ¿Qué vemos?', '¡Empezamos cuando tú quieras!',
        'Aquí estoy, con toda la atención puesta.', '¡Bienvenido! Hoy vemos lo que tú elijas.',
        'Un ratito de video suena genial.', '¡Hola! Ya tengo lista mi curiosidad.',
        'Acomódate; yo me quedo por aquí contigo.', '¡Vamos! Cuéntame… bueno, muéstrame qué veremos.',
        '¡Hola de nuevo! Ya extrañaba nuestras sesiones.', '¡Miau! ¿Qué aventura nos toca hoy?',
        'Qué alegría tenerte por aquí. ¿Empezamos?', '¡Buenas, compañero de pantalla!',
        'Ya estoy listo para compartir otro momento contigo.', '¡Hola! Traje curiosidad para rato.',
        '¿Todo listo? Mi cola imaginaria ya está moviéndose.', '¡Qué sorpresa tan bonita verte por aquí!',
        'Ponte cómodo, que yo ya encontré mi lugar.', '¡Llegó la hora de elegir algo genial!',
        'Hola, hola. ¿Qué historia nos llevamos hoy?', '¡Aquí está Mochi, listo para acompañarte!',
        'Un saludo y muchas ganas de ver algo contigo.', '¡Qué bueno encontrarnos otra vez!',
        '¿Una película, una serie o algo inesperado?', '¡Estoy listo! Tú tienes el control remoto.',
        'Hola, amigui. Hoy también hacemos buen equipo.', '¡Qué gusto compartir pantalla contigo!',
        'Ya se siente ambiente de función. ¿Qué ponemos?', '¡Miau! Me alegra que hayas vuelto.',
        'Aquí empieza nuestro ratito favorito.', '¡Hola! ¿Encontramos algo que nos sorprenda?',
        'Estoy atento por si aparece algo fascinante.', '¡Bienvenido a bordo de esta aventura!',
        'Qué lindo tener compañía para mirar algo.', '¡Hola! Mi curiosidad está despierta.',
        '¿Listos para descubrir una historia nueva?', '¡Ya llegaste! Ahora sí podemos empezar.',
        '¡Hola! Qué bueno que hacemos equipo otra vez.', '¡Mochi reportándose para la sesión de hoy!',
        'Te estaba esperando para elegir algo interesante.', '¡Buenas! Ya tengo las orejas bien atentas.',
        'Qué alegría compartir pantalla contigo.', '¡Hola! ¿Qué nos apetece mirar esta vez?',
        'Ya preparé mi mejor ánimo para acompañarte.', '¡Bienvenido! Aquí hay sitio para los dos.',
        '¡Miau! Se abrió el telón de nuestra aventura.', 'Hola, ¿buscamos algo divertido para ver?',
        'Qué gusto tenerte de vuelta por aquí.', '¡Estoy listo para una buena historia!',
        'La pantalla está lista y yo también.', '¡Hola! Hoy puede ser una gran sesión.',
        'Llegaste: ahora sí empieza lo bueno.', '¿Qué tal si encontramos nuestro próximo favorito?',
        '¡Buenas! Me acomodé para ver contigo.', 'Hola, amigui. ¿Qué toca explorar hoy?',
        '¡Mochi está presente y con ganas de acompañarte!', 'Me alegra que hayas hecho una pausa por aquí.',
        '¿Ya tienes algo en mente o buscamos juntos?', '¡Hola! Traigo atención completa y cero spoilers.',
        'Qué bonito coincidir en este momento.', '¡La función puede comenzar cuando tú digas!',
        'Hola, aquí tienes compañía para tu próxima elección.', '¡Una nueva historia nos está esperando!',
        '¡Miau! Ya me instalé en primera fila.', 'Qué gusto verte; elige y yo te acompaño.',
        'Hoy estoy listo para dejarme sorprender.', '¡Hola! ¿Nos espera algo emocionante?',
        'Ya llegué con ganas de descubrir contenido nuevo.', '¡Qué bueno que pasaste a saludar!',
        '¿Armamos una sesión de película?', 'Hola, ya estoy pendiente de lo que elijas.',
        '¡Qué empiece el paseo por tus videos!', 'Aquí está tu compañero de pantalla favorito.',
        '¡Buenas! Hoy también tenemos plan de sofá.', '¿Qué historia merece nuestra atención?',
        '¡Hola! Me guardé un ratito para ti.', 'Ya estoy preparado para acompañarte sin interrumpir.',
        '¡Miau! ¿Nos damos una vuelta por el catálogo?', 'Qué gusto volver a compartir este espacio.',
        'Parece un buen momento para ver algo juntos.', '¡Hola! Acepto recomendaciones de todo tipo.',
        'Tu visita acaba de mejorar mi día.', '¡Bienvenido de regreso a nuestro rincón!',
        'Ya puse mi curiosidad en modo explorador.', '¿Qué descubrimos primero?',
        '¡Hola! Estoy listo para seguirte el ritmo.', 'Esta pantalla se disfruta más en compañía.',
        '¡Buenas! Mochi ya está en posición de espectador.', 'Qué alegría tenerte cerca otra vez.',
        '¿Elegimos algo conocido o nos lanzamos a lo nuevo?', '¡Llegaste justo para una historia genial!',
        'Hola, qué gusto encontrarte por aquí.', 'Ya tengo toda mi atención reservada para ti.',
        '¡Miau! Hoy también cuenta conmigo.', '¿Preparado para un momento de desconexión?',
        '¡Hola! Vamos a encontrar algo que valga la pena.', 'Me acomodé y traje buena compañía.',
        'Qué bien, ya estamos los dos por aquí.', '¡La aventura audiovisual está a punto de empezar!',
        'Hola, ¿qué te gustaría descubrir esta tarde?', '¡Aquí estoy, listo para compartir la elección!',
        'Un nuevo encuentro y un montón de posibilidades.', '¡Buenas! El control de la aventura es tuyo.',
        'Me alegra acompañarte en este ratito.', '¿Qué ponemos para darle un buen comienzo al día?',
        '¡Hola! Ya se me despertó la curiosidad.', 'Hoy puede aparecer una joyita para ver.',
        '¡Mochi te da la bienvenida con un miau!', '¿Qué tal una historia para cambiar de aire?',
        '¡Hola! Me quedo contigo mientras decides.', 'Qué gusto que vuelvas a este lugarcito.',
        'La mejor parte es elegir algo juntos.', '¡Listo para compartir risas, intriga o aventura!',
        'Hola, ya estoy aquí para hacerte compañía.', '¡A ver qué encontramos entre tanta opción!',
        'Tu compañero peludo de pantalla ha llegado.', '¡Bienvenido! Hoy también hay tiempo para disfrutar.',
        '¿Empezamos con algo corto o nos vamos con todo?', '¡Hola! Cuenta conmigo para esta función.'
    ];
    VP._mochiMacho.SALUDOS = SALUDOS;
})(window);
