(function (window) {
    'use strict';

    var VP = window.VP;

    /* =====================================================================
       2. DIÁLOGOS Y TEXTOS
       ===================================================================== */
    var SALUDOS = [
        '¡Hola! Soy Mochi, tu asistente curiosa ♡', '¡Miau! Ya llegué para acompañarte ✨',
        '¡Qué bueno verte! ¿Qué te gustaría ver?', '¡La aventura está lista! ¿Qué veremos?',
        '¡Hola! Me alegra compartir este rato contigo. ♡', '¡Ya estoy aquí! ¿Qué historia nos espera?',
        '¿Le damos play? Yo ya estoy preparada.', '¡Qué gusto verte por aquí, amigui!',
        'Acomódate, que ya estoy lista para acompañarte.', '¿Qué veremos hoy? Tengo curiosidad.',
        '¡Llegaste justo a tiempo para la función!', 'Aquí estoy, preparada para una nueva aventura.',
        '¡Hola, hola! ¿Qué ponemos?', 'Ya encontré mi rinconcito. ¿Empezamos?',
        '¡Buenas! Prometo no tapar la pantalla.', 'Lista y atenta. Tú eliges el video.',
        '¡Qué emoción! Una historia nueva por descubrir.', '¡Hola! Hoy también puedo hacerte compañía.',
        'Me alegra coincidir contigo. ¿Le damos play?', '¡Presente! ¿Qué vamos a mirar?',
        'Aquí me tienes, lista para ver contigo.', '¡Ya llegué! Guárdame un lugarcito.',
        'Un video y buena compañía: suena perfecto.', '¡Hola, amigui! ¿Qué aventura elegimos?',
        'Ya estoy cómoda. Cuando quieras, empezamos.', '¡Lista para descubrir algo interesante!',
        'Qué gusto volver a este rinconcito contigo.', '¡Hola! A ver qué detalle curioso encontramos.',
        'La función está por comenzar; yo ya estoy lista.', '¡Qué bueno que volviste! ♡',
        'Preparada, atenta y sin spoilers. ¿Qué vemos?', '¡Empezamos cuando tú quieras!',
        'Aquí estoy, con toda la atención puesta.', '¡Qué bueno tenerte aquí! Hoy vemos lo que tú elijas.',
        'Un ratito de video suena genial.', '¡Hola! Ya tengo lista mi curiosidad.',
        'Acomódate; yo me quedo por aquí contigo.', '¡Vamos! Cuéntame… bueno, muéstrame qué veremos.',
        '¡Hola de nuevo! Ya extrañaba nuestras sesiones.', '¡Miau! ¿Qué aventura nos toca hoy?',
        'Qué alegría tenerte por aquí. ¿Empezamos?', '¡Buenas! Aquí está tu compañía de pantalla.',
        'Ya estoy lista para compartir otro momento contigo.', '¡Hola! Traje curiosidad para rato.',
        '¿Está todo listo? Mi cola imaginaria ya está moviéndose.', '¡Qué sorpresa tan bonita verte por aquí!',
        'Ponte a gusto, que yo ya encontré mi lugar.', '¡Llegó la hora de elegir algo genial!',
        'Hola, hola. ¿Qué historia nos llevamos hoy?', '¡Aquí está Mochi, lista para acompañarte!',
        'Un saludo y muchas ganas de ver algo contigo.', '¡Qué bueno encontrarnos otra vez!',
        '¿Una película, una serie o algo inesperado?', '¡Estoy lista! Tú tienes el control remoto.',
        'Hola, amigui. Hoy también hacemos buen equipo.', '¡Qué gusto compartir pantalla contigo!',
        'Ya se siente ambiente de función. ¿Qué ponemos?', '¡Miau! Me alegra que hayas vuelto.',
        'Aquí empieza nuestro ratito favorito.', '¡Hola! ¿Encontramos algo que nos sorprenda?',
        'Estoy atenta por si aparece algo fascinante.', '¡Qué bueno tenerte a bordo de esta aventura!',
        'Qué lindo tener compañía para mirar algo.', '¡Hola! Mi curiosidad está despierta.',
        '¿Descubrimos una historia nueva?', '¡Ya llegaste! Ahora sí podemos empezar.',
        '¡Hola! Qué bueno que hacemos equipo otra vez.', '¡Mochi reportándose para la sesión de hoy!',
        'Te estaba esperando para elegir algo interesante.', '¡Buenas! Ya tengo las orejas bien atentas.',
        'Qué alegría compartir pantalla contigo.', '¡Hola! ¿Qué nos apetece mirar esta vez?',
        'Ya preparé mi mejor ánimo para acompañarte.', '¡Qué bueno tenerte aquí! Hay sitio para compartir.',
        '¡Miau! Se abrió el telón de nuestra aventura.', 'Hola, ¿buscamos algo divertido para ver?',
        'Qué gusto tenerte de vuelta por aquí.', '¡Estoy lista para una buena historia!',
        'La pantalla está lista y yo también.', '¡Hola! Hoy puede ser una gran sesión.',
        'Llegaste: ahora sí empieza lo bueno.', '¿Qué tal si encontramos nuestro próximo favorito?',
        '¡Buenas! Me acomodé para ver contigo.', 'Hola, amigui. ¿Qué toca explorar hoy?',
        '¡Mochi está presente y con ganas de acompañarte!', 'Me alegra que hayas hecho una pausa por aquí.',
        '¿Ya tienes algo en mente o buscamos qué ver?', '¡Hola! Traigo atención completa y cero spoilers.',
        'Qué bonito coincidir en este momento.', '¡La función puede comenzar cuando tú digas!',
        'Hola, aquí tienes compañía para tu próxima elección.', '¡Una nueva historia nos está esperando!',
        '¡Miau! Ya me instalé en primera fila.', 'Qué gusto verte; elige y yo te acompaño.',
        'Hoy estoy lista para dejarme sorprender.', '¡Hola! ¿Nos espera algo emocionante?',
        'Ya llegué con ganas de descubrir contenido nuevo.', '¡Qué bueno que pasaste a saludar!',
        '¿Armamos una sesión de película?', 'Hola, ya estoy pendiente de lo que elijas.',
        '¡Qué empiece el paseo por tus videos!', 'Aquí está tu compañera de pantalla favorita.',
        '¡Buenas! Hoy también tenemos plan de sofá.', '¿Qué historia merece nuestra atención?',
        '¡Hola! Me guardé un ratito para ti.', 'Ya estoy preparada para acompañarte sin interrumpir.',
        '¡Miau! ¿Nos damos una vuelta por el catálogo?', 'Qué gusto volver a compartir este espacio.',
        'Parece un buen momento para ver algo en compañía.', '¡Hola! Acepto recomendaciones de todo tipo.',
        'Tu visita acaba de mejorar mi día.', '¡Qué bueno tenerte de vuelta en nuestro rincón!',
        'Ya puse mi curiosidad en modo explorador.', '¿Qué descubrimos primero?',
        '¡Hola! Estoy lista para seguirte el ritmo.', 'Esta pantalla se disfruta más en compañía.',
        '¡Buenas! Mochi ya está en posición de espectador.', 'Qué alegría tenerte cerca otra vez.',
        '¿Elegimos algo conocido o nos lanzamos a lo nuevo?', '¡Llegaste justo para una historia genial!',
        'Hola, qué gusto encontrarte por aquí.', 'Ya tengo toda mi atención reservada para ti.',
        '¡Miau! Hoy también cuenta conmigo.', '¿Te apetece un momento de desconexión?',
        '¡Hola! Vamos a encontrar algo que valga la pena.', 'Me acomodé y traje buena compañía.',
        'Qué bien, ya estamos los dos por aquí.', '¡La aventura audiovisual está a punto de empezar!',
        'Hola, ¿qué te gustaría descubrir esta tarde?', '¡Aquí estoy, lista para compartir la elección!',
        'Un nuevo encuentro y un montón de posibilidades.', '¡Buenas! El control de la aventura es tuyo.',
        'Me alegra acompañarte en este ratito.', '¿Qué ponemos para darle un buen comienzo al día?',
        '¡Hola! Ya se me despertó la curiosidad.', 'Hoy puede aparecer una joyita para ver.',
        '¡Mochi te da la bienvenida con un miau!', '¿Qué tal una historia para cambiar de aire?',
        '¡Hola! Me quedo contigo mientras decides.', 'Qué gusto que vuelvas a este lugarcito.',
        'La mejor parte es elegir qué ver.', '¡Lista para compartir risas, intriga o aventura!',
        'Hola, ya estoy aquí para hacerte compañía.', '¡A ver qué encontramos entre tanta opción!',
        'Tu compañera peluda de pantalla ha llegado.', '¡Qué bueno tenerte aquí! Hoy también hay tiempo para disfrutar.',
        '¿Empezamos con algo corto o nos vamos con todo?', '¡Hola! Cuenta conmigo para esta función.'
    ];
    VP._mochiHembra.SALUDOS = SALUDOS;
})(window);

